import type { CreatureDefinition } from '../types';

export const CREATURE_VOID_CRAWLER: CreatureDefinition = {
  id: 'creature_void_crawler',
  displayName: 'Void Crawler',
  description: 'Small, skittering omnivore of the scarred plains. Will attack when hungry and target appears smaller.',
  entityClass: 'creature',
  biomes: ['void_plains'],
  textureKey: 'creature_void_crawler',
  color: 0x4a4a5a,
  lootTableId: 'loot_creature_void_crawler',
  behavior: 'omnivore',
  baseHealth: 80,
  levelRange: [1, 5],
  baseXp: 15,
  respawnSeconds: 180,
};

export const CREATURE_CANOPY_GRAZER: CreatureDefinition = {
  id: 'creature_canopy_grazer',
  displayName: 'Canopy Grazer',
  description: 'Large herbivore feeding on fungal-tree canopy. Docile unless cornered.',
  entityClass: 'creature',
  biomes: ['fungal_forest'],
  textureKey: 'creature_canopy_grazer',
  color: 0x44cc88,
  lootTableId: 'loot_creature_canopy_grazer',
  behavior: 'herbivore',
  baseHealth: 100,
  levelRange: [1, 6],
  baseXp: 20,
  respawnSeconds: 240,
};

export const CREATURE_SPORE_CARRIER: CreatureDefinition = {
  id: 'creature_spore_carrier',
  displayName: 'Spore Carrier',
  description: 'Fungal creature that spreads spores when disturbed. Opportunistic feeder.',
  entityClass: 'creature',
  biomes: ['fungal_forest'],
  textureKey: 'creature_spore_carrier',
  color: 0x9370db,
  lootTableId: 'loot_creature_spore_carrier',
  behavior: 'omnivore',
  baseHealth: 120,
  levelRange: [4, 12],
  baseXp: 25,
  respawnSeconds: 300,
};

export const CREATURE_CRYSTAL_HUNTER: CreatureDefinition = {
  id: 'creature_crystal_hunter',
  displayName: 'Crystal Hunter',
  description: 'Predator with crystalline integument. Uses light refraction to disorient prey.',
  entityClass: 'creature',
  biomes: ['crystal_caves'],
  textureKey: 'creature_crystal_hunter',
  color: 0x7b68ee,
  lootTableId: 'loot_creature_crystal_hunter',
  behavior: 'predator',
  baseHealth: 160,
  levelRange: [8, 18],
  baseXp: 45,
  respawnSeconds: 420,
};

export const CREATURE_MARSH_LURKER: CreatureDefinition = {
  id: 'creature_marsh_lurker',
  displayName: 'Marsh Lurker',
  description: 'Toxin-resistant predator of the miasma marshes. Uses chemical environment as weapon.',
  entityClass: 'creature',
  biomes: ['miasma_marshes'],
  textureKey: 'creature_marsh_lurker',
  color: 0x6b8e23,
  lootTableId: 'loot_creature_marsh_lurker',
  behavior: 'predator',
  baseHealth: 140,
  levelRange: [5, 15],
  baseXp: 40,
  respawnSeconds: 360,
};

export const CREATURE_DART_RUNNER: CreatureDefinition = {
  id: 'creature_dart_runner',
  displayName: 'Dart Runner',
  description: 'Swift predator of the petrified expanse. Must keep moving to avoid calcification.',
  entityClass: 'creature',
  biomes: ['petrified_expanse'],
  textureKey: 'creature_dart_runner',
  color: 0xa9a9a9,
  lootTableId: 'loot_creature_dart_runner',
  behavior: 'predator',
  baseHealth: 130,
  levelRange: [6, 16],
  baseXp: 38,
  respawnSeconds: 360,
};

export const CREATURE_FROST_STALKER: CreatureDefinition = {
  id: 'creature_frost_stalker',
  displayName: 'Frost Stalker',
  description: 'Marathon hunter of the frozen reaches. Outlasts prey through superior cold adaptation.',
  entityClass: 'creature',
  biomes: ['frozen_expanse'],
  textureKey: 'creature_frost_stalker',
  color: 0xb0e0e6,
  lootTableId: 'loot_creature_frost_stalker',
  behavior: 'predator',
  baseHealth: 200,
  levelRange: [10, 22],
  baseXp: 55,
  respawnSeconds: 480,
};

export const CREATURE_MAGMA_BEAST: CreatureDefinition = {
  id: 'creature_magma_beast',
  displayName: 'Magma Beast',
  description: 'Armored silicon predator thriving in extreme heat. Slow but devastating.',
  entityClass: 'creature',
  biomes: ['volcanic_ridge'],
  textureKey: 'creature_magma_beast',
  color: 0xff4500,
  lootTableId: 'loot_creature_magma_beast',
  behavior: 'predator',
  baseHealth: 220,
  levelRange: [12, 28],
  baseXp: 70,
  respawnSeconds: 600,
};

export const CREATURE_TOXIC_LURKER: CreatureDefinition = {
  id: 'creature_toxic_lurker',
  displayName: 'Toxic Lurker',
  description: 'Camouflaged predator of toxic wastes. Secretes corrosive compounds.',
  entityClass: 'creature',
  biomes: ['toxic_wastes'],
  textureKey: 'creature_toxic_lurker',
  color: 0x9acd32,
  lootTableId: 'loot_creature_toxic_lurker',
  behavior: 'predator',
  baseHealth: 150,
  levelRange: [8, 20],
  baseXp: 50,
  respawnSeconds: 420,
};

export const CREATURE_VOID_HORROR: CreatureDefinition = {
  id: 'creature_void_horror',
  displayName: 'Void Horror',
  description: 'Anomaly-corrupted abomination. Attacks anything it perceives without regard for self-preservation.',
  entityClass: 'creature',
  biomes: ['ancient_ruins', 'starfall_crater'],
  textureKey: 'creature_void_horror',
  color: 0x191970,
  lootTableId: 'loot_creature_void_horror',
  behavior: 'maniac',
  baseHealth: 320,
  levelRange: [20, 35],
  baseXp: 120,
  respawnSeconds: 900,
};

export const CREATURE_COASTAL_SCUTTLER: CreatureDefinition = {
  id: 'creature_coastal_scuttler',
  displayName: 'Coastal Scuttler',
  description: 'Small crustacean-like creature that feeds on exposed minerals. Docile unless stepped on — at which point it becomes surprisingly aggressive for its size.',
  entityClass: 'creature',
  biomes: ['void_plains'],
  textureKey: 'creature_coastal_scuttler',
  color: 0x6b7280,
  lootTableId: 'loot_creature_coastal_scuttler',
  behavior: 'herbivore',
  baseHealth: 70,
  levelRange: [1, 4],
  baseXp: 12,
  respawnSeconds: 180,
};

export const CREATURE_ASH_SKIMMER: CreatureDefinition = {
  id: 'creature_ash_skimmer',
  displayName: 'Ash Skimmer',
  description: 'A heat-adapted flyer that glides on thermal updrafts in volcanic regions. Feeds on thermal vent bacteria and unwary smaller creatures.',
  entityClass: 'creature',
  biomes: ['volcanic_ridge'],
  textureKey: 'creature_ash_skimmer',
  color: 0xdc2626,
  lootTableId: 'loot_creature_ash_skimmer',
  behavior: 'omnivore',
  baseHealth: 140,
  levelRange: [10, 20],
  baseXp: 45,
  respawnSeconds: 360,
};

export const CREATURE_MIASMA_DRIFTER: CreatureDefinition = {
  id: 'creature_miasma_drifter',
  displayName: 'Miasma Drifter',
  description: 'A buoyant organism that floats through the toxic marshes, filtering nutrients from the chemical-laden air. Harmless unless cornered.',
  entityClass: 'creature',
  biomes: ['miasma_marshes'],
  textureKey: 'creature_miasma_drifter',
  color: 0x84cc16,
  lootTableId: 'loot_creature_miasma_drifter',
  behavior: 'herbivore',
  baseHealth: 100,
  levelRange: [3, 10],
  baseXp: 22,
  respawnSeconds: 240,
};

export const CREATURE_ICE_BURROWER: CreatureDefinition = {
  id: 'creature_ice_burrower',
  displayName: 'Ice Burrower',
  description: 'An armored predator that tunnels through permafrost to ambush prey from below. The only warning is a faint vibration before it strikes.',
  entityClass: 'creature',
  biomes: ['frozen_expanse'],
  textureKey: 'creature_ice_burrower',
  color: 0x3b82f6,
  lootTableId: 'loot_creature_ice_burrower',
  behavior: 'predator',
  baseHealth: 210,
  levelRange: [12, 24],
  baseXp: 60,
  respawnSeconds: 480,
};

export const CREATURE_CRYSTAL_CRAWLER: CreatureDefinition = {
  id: 'creature_crystal_crawler',
  displayName: 'Crystal Crawler',
  description: 'A slow-moving grazer that consumes crystalline lattice-moss. Its shell is composed of absorbed silicon, making it surprisingly durable.',
  entityClass: 'creature',
  biomes: ['crystal_caves'],
  textureKey: 'creature_crystal_crawler',
  color: 0xa78bfa,
  lootTableId: 'loot_creature_crystal_crawler',
  behavior: 'herbivore',
  baseHealth: 110,
  levelRange: [5, 12],
  baseXp: 25,
  respawnSeconds: 300,
};

export const CREATURE_RUIN_SEEKER: CreatureDefinition = {
  id: 'creature_ruin_seeker',
  displayName: 'Ruin Seeker',
  description: 'A creature drawn to Ancient technology for unknown reasons. Highly territorial around ruins and far more intelligent than its appearance suggests.',
  entityClass: 'creature',
  biomes: ['ancient_ruins'],
  textureKey: 'creature_ruin_seeker',
  color: 0x78716c,
  lootTableId: 'loot_creature_ruin_seeker',
  behavior: 'predator',
  baseHealth: 280,
  levelRange: [18, 30],
  baseXp: 90,
  respawnSeconds: 600,
};

export const CREATURE_PETRIFIED_LURKER: CreatureDefinition = {
  id: 'creature_petrified_lurker',
  displayName: 'Petrified Lurker',
  description: 'A camouflaged ambush predator that remains motionless among stone trees, waiting for prey. It can suppress the calcification process through unknown biological means.',
  entityClass: 'creature',
  biomes: ['petrified_expanse'],
  textureKey: 'creature_petrified_lurker',
  color: 0x57534e,
  lootTableId: 'loot_creature_petrified_lurker',
  behavior: 'predator',
  baseHealth: 145,
  levelRange: [8, 18],
  baseXp: 42,
  respawnSeconds: 360,
};

// ===== PHASE 88 ADDITIONS =====

export const CREATURE_STARFALL_GRAZER: CreatureDefinition = {
  id: 'creature_starfall_grazer',
  displayName: 'Starfall Grazer',
  description: 'Alien herbivore feeding on anomaly-mutated vegetation. Docile but unpredictable due to void exposure.',
  entityClass: 'creature',
  biomes: ['starfall_crater'],
  textureKey: 'creature_starfall_grazer',
  color: 0x4a5568,
  lootTableId: 'loot_creature_starfall_grazer',
  behavior: 'herbivore',
  baseHealth: 130,
  levelRange: [12, 22],
  baseXp: 35,
  respawnSeconds: 300,
};

export const CREATURE_CRATER_STALKER: CreatureDefinition = {
  id: 'creature_crater_stalker',
  displayName: 'Crater Stalker',
  description: 'Apex predator adapted to anomaly zones. Uses dimensional instability to ambush prey with devastating efficiency.',
  entityClass: 'creature',
  biomes: ['starfall_crater'],
  textureKey: 'creature_crater_stalker',
  color: 0x4a0080,
  lootTableId: 'loot_creature_crater_stalker',
  behavior: 'predator',
  baseHealth: 200,
  levelRange: [15, 25],
  baseXp: 70,
  respawnSeconds: 420,
};

export const CREATURE_GUARDIAN_CONSTRUCT: CreatureDefinition = {
  id: 'creature_guardian_construct',
  displayName: 'Guardian Construct',
  description: 'Ancient automaton still following defense protocols. Attacks trespassers in ruin zones with mechanical precision.',
  entityClass: 'creature',
  biomes: ['ancient_ruins'],
  textureKey: 'creature_guardian_construct',
  color: 0x8b7355,
  lootTableId: 'loot_creature_guardian_construct',
  behavior: 'predator',
  baseHealth: 180,
  levelRange: [14, 24],
  baseXp: 65,
  respawnSeconds: 420,
};

export const CREATURE_RELIC_BEAST: CreatureDefinition = {
  id: 'creature_relic_beast',
  displayName: 'Relic Beast',
  description: 'Mutated creature warped by prolonged ruin exposure. Territorial and far more intelligent than its appearance suggests.',
  entityClass: 'creature',
  biomes: ['ancient_ruins'],
  textureKey: 'creature_relic_beast',
  color: 0xa0522d,
  lootTableId: 'loot_creature_relic_beast',
  behavior: 'omnivore',
  baseHealth: 160,
  levelRange: [10, 20],
  baseXp: 50,
  respawnSeconds: 360,
};

// ===== PHASE 110 — Tier I Biome Creature Population =====

export const CREATURE_PLAINS_GRAZER: CreatureDefinition = {
  id: 'creature_plains_grazer',
  displayName: 'Plains Grazer',
  description: 'Slow-moving herd animal that feeds on void-adapted grasses. Docile and easily startled.',
  entityClass: 'creature',
  biomes: ['void_plains'],
  textureKey: 'creature_plains_grazer',
  color: 0x8a8a6a,
  lootTableId: 'loot_creature_plains_grazer',
  behavior: 'herbivore',
  baseHealth: 70,
  levelRange: [1, 3],
  baseXp: 10,
  respawnSeconds: 180,
};

export const CREATURE_VOID_PROWLER: CreatureDefinition = {
  id: 'creature_void_prowler',
  displayName: 'Void Prowler',
  description: 'Lean, quick predator that hunts in the open plains. Ambushes from behind rocky outcrops.',
  entityClass: 'creature',
  biomes: ['void_plains'],
  textureKey: 'creature_void_prowler',
  color: 0x3a3a5a,
  lootTableId: 'loot_creature_void_prowler',
  behavior: 'predator',
  baseHealth: 95,
  levelRange: [3, 6],
  baseXp: 18,
  respawnSeconds: 240,
};

export const CREATURE_MYCELIAL_STALKER: CreatureDefinition = {
  id: 'creature_mycelial_stalker',
  displayName: 'Mycelial Stalker',
  description: 'Silent hunter that moves through fungal undergrowth. Uses chemical lures to attract prey.',
  entityClass: 'creature',
  biomes: ['fungal_forest'],
  textureKey: 'creature_mycelial_stalker',
  color: 0x554488,
  lootTableId: 'loot_creature_mycelial_stalker',
  behavior: 'predator',
  baseHealth: 90,
  levelRange: [3, 6],
  baseXp: 18,
  respawnSeconds: 240,
};

export const CREATURE_SPORE_BEETLE: CreatureDefinition = {
  id: 'creature_spore_beetle',
  displayName: 'Spore Beetle',
  description: 'Armored beetle that feeds on fungal fruiting bodies. Releases defensive spore clouds when threatened.',
  entityClass: 'creature',
  biomes: ['fungal_forest'],
  textureKey: 'creature_spore_beetle',
  color: 0x668844,
  lootTableId: 'loot_creature_spore_beetle',
  behavior: 'herbivore',
  baseHealth: 80,
  levelRange: [1, 4],
  baseXp: 12,
  respawnSeconds: 200,
};

export const CREATURE_RUIN_SCAVENGER: CreatureDefinition = {
  id: 'creature_ruin_scavenger',
  displayName: 'Ruin Scavenger',
  description: 'Small, quick creature that picks through Ancient refuse. Skittish but will bite if cornered.',
  entityClass: 'creature',
  biomes: ['ancient_ruins'],
  textureKey: 'creature_ruin_scavenger',
  color: 0xaa8855,
  lootTableId: 'loot_creature_ruin_scavenger',
  behavior: 'omnivore',
  baseHealth: 75,
  levelRange: [1, 4],
  baseXp: 12,
  respawnSeconds: 180,
};

export const CREATURE_RUIN_WARDEN: CreatureDefinition = {
  id: 'creature_ruin_warden',
  displayName: 'Ruin Warden',
  description: 'Large territorial predator that nests in Ancient structures. Fiercely defends its claimed ruins.',
  entityClass: 'creature',
  biomes: ['ancient_ruins'],
  textureKey: 'creature_ruin_warden',
  color: 0x886644,
  lootTableId: 'loot_creature_ruin_warden',
  behavior: 'predator',
  baseHealth: 100,
  levelRange: [4, 6],
  baseXp: 20,
  respawnSeconds: 240,
};

// ===== PHASE 110 — Tier II Biome Creature Population =====

export const CREATURE_SLUDGE_GRAZER: CreatureDefinition = {
  id: 'creature_sludge_grazer',
  displayName: 'Sludge Grazer',
  description: 'Squat, armored creature that filters nutrients from toxic pools. Its shell is heavily corroded but functionally impervious to acid.',
  entityClass: 'creature',
  biomes: ['toxic_wastes'],
  textureKey: 'creature_sludge_grazer',
  color: 0x667744,
  lootTableId: 'loot_creature_sludge_grazer',
  behavior: 'herbivore',
  baseHealth: 120,
  levelRange: [7, 14],
  baseXp: 28,
  respawnSeconds: 300,
};

export const CREATURE_CORROSION_MAW: CreatureDefinition = {
  id: 'creature_corrosion_maw',
  displayName: 'Corrosion Maw',
  description: 'Ambush predator with acid-etched jaws. Lurks in chemical pools, striking when prey approaches to drink.',
  entityClass: 'creature',
  biomes: ['toxic_wastes'],
  textureKey: 'creature_corrosion_maw',
  color: 0x7dbb00,
  lootTableId: 'loot_creature_corrosion_maw',
  behavior: 'predator',
  baseHealth: 150,
  levelRange: [10, 18],
  baseXp: 45,
  respawnSeconds: 360,
};

export const CREATURE_FUME_DRIFTER: CreatureDefinition = {
  id: 'creature_fume_drifter',
  displayName: 'Fume Drifter',
  description: 'Floating scavenger that feeds on chemical vapors and decomposing matter. Releases toxic clouds when disturbed.',
  entityClass: 'creature',
  biomes: ['toxic_wastes'],
  textureKey: 'creature_fume_drifter',
  color: 0x889944,
  lootTableId: 'loot_creature_fume_drifter',
  behavior: 'omnivore',
  baseHealth: 110,
  levelRange: [8, 15],
  baseXp: 32,
  respawnSeconds: 300,
};

export const CREATURE_ACID_MANIAC: CreatureDefinition = {
  id: 'creature_acid_maniac',
  displayName: 'Acid Maniac',
  description: 'Creature driven to chemical-fueled frenzy. Corroded beyond recognition, it attacks anything it detects without self-preservation.',
  entityClass: 'creature',
  biomes: ['toxic_wastes'],
  textureKey: 'creature_acid_maniac',
  color: 0xccdd00,
  lootTableId: 'loot_creature_acid_maniac',
  behavior: 'maniac',
  baseHealth: 200,
  levelRange: [12, 20],
  baseXp: 65,
  respawnSeconds: 600,
};

export const CREATURE_BOG_CRAWLER: CreatureDefinition = {
  id: 'creature_bog_crawler',
  displayName: 'Bog Crawler',
  description: 'Slow-moving amphibian that grazes on marsh vegetation. Tough hide provides natural toxin resistance.',
  entityClass: 'creature',
  biomes: ['miasma_marshes'],
  textureKey: 'creature_bog_crawler',
  color: 0x556633,
  lootTableId: 'loot_creature_bog_crawler',
  behavior: 'herbivore',
  baseHealth: 130,
  levelRange: [7, 15],
  baseXp: 30,
  respawnSeconds: 300,
};

export const CREATURE_MARSH_SNAPPER: CreatureDefinition = {
  id: 'creature_marsh_snapper',
  displayName: 'Marsh Snapper',
  description: 'Opportunistic feeder lurking in shallow water. Snatches anything small enough to swallow.',
  entityClass: 'creature',
  biomes: ['miasma_marshes'],
  textureKey: 'creature_marsh_snapper',
  color: 0x445544,
  lootTableId: 'loot_creature_marsh_snapper',
  behavior: 'omnivore',
  baseHealth: 115,
  levelRange: [8, 16],
  baseXp: 34,
  respawnSeconds: 300,
};

export const CREATURE_STONE_GRAZER: CreatureDefinition = {
  id: 'creature_stone_grazer',
  displayName: 'Stone Grazer',
  description: 'Heavily calcified creature that feeds on mineral-rich lichen. Moves slowly but has near-impenetrable petrified armor.',
  entityClass: 'creature',
  biomes: ['petrified_expanse'],
  textureKey: 'creature_stone_grazer',
  color: 0x998877,
  lootTableId: 'loot_creature_stone_grazer',
  behavior: 'herbivore',
  baseHealth: 140,
  levelRange: [7, 14],
  baseXp: 28,
  respawnSeconds: 300,
};

export const CREATURE_FOSSIL_SCAVENGER: CreatureDefinition = {
  id: 'creature_fossil_scavenger',
  displayName: 'Fossil Scavenger',
  description: 'Quick, adaptable creature picking through petrified remains. Strips minerals from fossilized matter.',
  entityClass: 'creature',
  biomes: ['petrified_expanse'],
  textureKey: 'creature_fossil_scavenger',
  color: 0x887766,
  lootTableId: 'loot_creature_fossil_scavenger',
  behavior: 'omnivore',
  baseHealth: 105,
  levelRange: [8, 16],
  baseXp: 32,
  respawnSeconds: 280,
};

export const ALL_CREATURES: readonly CreatureDefinition[] = [
  CREATURE_VOID_CRAWLER,
  CREATURE_CANOPY_GRAZER,
  CREATURE_SPORE_CARRIER,
  CREATURE_CRYSTAL_HUNTER,
  CREATURE_MARSH_LURKER,
  CREATURE_DART_RUNNER,
  CREATURE_FROST_STALKER,
  CREATURE_MAGMA_BEAST,
  CREATURE_TOXIC_LURKER,
  CREATURE_VOID_HORROR,
  CREATURE_COASTAL_SCUTTLER,
  CREATURE_ASH_SKIMMER,
  CREATURE_MIASMA_DRIFTER,
  CREATURE_ICE_BURROWER,
  CREATURE_CRYSTAL_CRAWLER,
  CREATURE_RUIN_SEEKER,
  CREATURE_PETRIFIED_LURKER,
  // Phase 88 starfall_crater and ancient_ruins creatures
  CREATURE_STARFALL_GRAZER,
  CREATURE_CRATER_STALKER,
  CREATURE_GUARDIAN_CONSTRUCT,
  CREATURE_RELIC_BEAST,
  // Phase 110 Tier I creatures
  CREATURE_PLAINS_GRAZER,
  CREATURE_VOID_PROWLER,
  CREATURE_MYCELIAL_STALKER,
  CREATURE_SPORE_BEETLE,
  CREATURE_RUIN_SCAVENGER,
  CREATURE_RUIN_WARDEN,
  // Phase 110 Tier II creatures
  CREATURE_SLUDGE_GRAZER,
  CREATURE_CORROSION_MAW,
  CREATURE_FUME_DRIFTER,
  CREATURE_ACID_MANIAC,
  CREATURE_BOG_CRAWLER,
  CREATURE_MARSH_SNAPPER,
  CREATURE_STONE_GRAZER,
  CREATURE_FOSSIL_SCAVENGER,
];
