import Phaser from 'phaser';

export class PreloadScene extends Phaser.Scene {
  constructor() {
    super({ key: 'PreloadScene' });
  }

  preload(): void {
    // Create loading bar
    const width = this.cameras.main.width;
    const height = this.cameras.main.height;

    const progressBar = this.add.graphics();
    const progressBox = this.add.graphics();
    progressBox.fillStyle(0x1e1e2e, 0.8);
    progressBox.fillRect(width / 2 - 160, height / 2 - 25, 320, 50);

    const loadingText = this.add.text(width / 2, height / 2 - 50, 'Loading...', {
      fontSize: '20px',
      color: '#e0e0e0',
    });
    loadingText.setOrigin(0.5, 0.5);

    const percentText = this.add.text(width / 2, height / 2, '0%', {
      fontSize: '18px',
      color: '#e0e0e0',
    });
    percentText.setOrigin(0.5, 0.5);

    // Update progress bar
    this.load.on('progress', (value: number) => {
      percentText.setText(`${Math.round(value * 100)}%`);
      progressBar.clear();
      progressBar.fillStyle(0x7b68ee, 1);
      progressBar.fillRect(width / 2 - 150, height / 2 - 15, 300 * value, 30);
    });

    this.load.on('complete', () => {
      progressBar.destroy();
      progressBox.destroy();
      loadingText.destroy();
      percentText.destroy();
    });

    // Load game assets
    this.loadAssets();
  }

  private loadAssets(): void {
    this.load.setPath('assets/');

    // Load floor tile sprites from PNG files (generated by sprite-generator)
    this.loadFloorTileSprites();

    // Generate procedural textures for walls, formations, and entities
    this.generateTileTextures();
  }

  private loadFloorTileSprites(): void {
    // Load all 8 biome floor tiles from sprite-generator output
    const floorTiles = [
      'tile_void_floor',
      'tile_crystal_floor',
      'tile_toxic_floor',
      'tile_ruins_floor',
      'tile_ice_floor',
      'tile_volcanic_floor',
      'tile_fungal_floor',
      'tile_crater_floor',
    ];

    for (const key of floorTiles) {
      this.load.image(key, `sprites/${key}.png`);
    }
  }

  private generateTileTextures(): void {
    const TILE_SIZE = 96;
    const graphics = this.make.graphics({ x: 0, y: 0 });

    // Generate wall/formation textures (floor tiles now loaded from PNG)
    const tileTextures = [
      // Void Plains
      { key: 'tile_void_wall', color: 0x1a1a2a, border: 0x0a0a1a },
      // Crystal Caves
      { key: 'tile_crystal_formation', color: 0x7b68ee, border: 0x6b58de },
      // Toxic Wastes
      { key: 'tile_toxic_pool', color: 0x9acd32, border: 0x8abd22 },
      // Ancient Ruins
      { key: 'tile_ruins_wall', color: 0x8b7355, border: 0x7b6345 },
      // Frozen Expanse
      { key: 'tile_ice_wall', color: 0xb0e0e6, border: 0xa0d0d6 },
      // Volcanic Ridge
      { key: 'tile_lava', color: 0xff4500, border: 0xef3500 },
      // Fungal Forest
      { key: 'tile_fungal_growth', color: 0x9370db, border: 0x8360cb },
      // Starfall Crater
      { key: 'tile_crater_debris', color: 0x191970, border: 0x090960 },
    ];

    // Generate each tile texture
    for (const tile of tileTextures) {
      graphics.fillStyle(tile.color);
      graphics.fillRect(0, 0, TILE_SIZE, TILE_SIZE);
      graphics.lineStyle(1, tile.border);
      graphics.strokeRect(0, 0, TILE_SIZE, TILE_SIZE);
      graphics.generateTexture(tile.key, TILE_SIZE, TILE_SIZE);
      graphics.clear();
    }

    // Player sphere - higher resolution with shading for 3D effect
    const PLAYER_SIZE = 192; // 2x resolution for crisp rendering
    const center = PLAYER_SIZE / 2;
    const radius = 70;

    // Base sphere color
    graphics.fillStyle(0x7b68ee);
    graphics.fillCircle(center, center, radius);

    // Highlight (top-left) for 3D sphere effect
    graphics.fillStyle(0x9f8fff, 0.6);
    graphics.fillCircle(center - radius * 0.3, center - radius * 0.3, radius * 0.5);

    // Smaller bright highlight
    graphics.fillStyle(0xffffff, 0.4);
    graphics.fillCircle(center - radius * 0.4, center - radius * 0.4, radius * 0.2);

    // Dark edge (bottom-right) for depth
    graphics.lineStyle(3, 0x5040a0, 0.5);
    graphics.beginPath();
    graphics.arc(center, center, radius - 1, Math.PI * 0.1, Math.PI * 0.9);
    graphics.strokePath();

    // Outer ring for definition
    graphics.lineStyle(2, 0x3a2a7a, 0.8);
    graphics.strokeCircle(center, center, radius);

    graphics.generateTexture('player', PLAYER_SIZE, PLAYER_SIZE);
    graphics.clear();

    // Creature (centered at 48,48 for 96px tile)
    graphics.fillStyle(0xff4444);
    graphics.fillCircle(48, 48, 30);
    graphics.generateTexture('creature', TILE_SIZE, TILE_SIZE);
    graphics.clear();

    // Mineral (centered square for 96px tile)
    graphics.fillStyle(0x44ffff);
    graphics.fillRect(24, 24, 48, 48);
    graphics.generateTexture('mineral', TILE_SIZE, TILE_SIZE);
    graphics.clear();

    // Item (smaller circle centered for 96px tile)
    graphics.fillStyle(0xffff44);
    graphics.fillCircle(48, 48, 18);
    graphics.generateTexture('item', TILE_SIZE, TILE_SIZE);
    graphics.clear();

    // Plant (triangle centered for 96px tile)
    graphics.fillStyle(0x44cc44); // green
    graphics.fillTriangle(
      48, 12,  // top
      24, 84,  // bottom left
      72, 84   // bottom right
    );
    graphics.generateTexture('plant', TILE_SIZE, TILE_SIZE);
    graphics.clear();

    graphics.destroy();
  }

  create(): void {
    this.scene.start('WorldScene');
  }
}
