import Phaser from 'phaser';

export class PreloadScene extends Phaser.Scene {
  constructor() {
    super({ key: 'PreloadScene' });
  }

  preload(): void {
    // Create loading bar
    const width = this.cameras.main.width;
    const height = this.cameras.main.height;

    const progressBar = this.add.graphics();
    const progressBox = this.add.graphics();
    progressBox.fillStyle(0x1e1e2e, 0.8);
    progressBox.fillRect(width / 2 - 160, height / 2 - 25, 320, 50);

    const loadingText = this.add.text(width / 2, height / 2 - 50, 'Loading...', {
      fontSize: '20px',
      color: '#e0e0e0',
    });
    loadingText.setOrigin(0.5, 0.5);

    const percentText = this.add.text(width / 2, height / 2, '0%', {
      fontSize: '18px',
      color: '#e0e0e0',
    });
    percentText.setOrigin(0.5, 0.5);

    // Update progress bar
    this.load.on('progress', (value: number) => {
      percentText.setText(`${Math.round(value * 100)}%`);
      progressBar.clear();
      progressBar.fillStyle(0x7b68ee, 1);
      progressBar.fillRect(width / 2 - 150, height / 2 - 15, 300 * value, 30);
    });

    this.load.on('complete', () => {
      progressBar.destroy();
      progressBox.destroy();
      loadingText.destroy();
      percentText.destroy();
    });

    // Load game assets
    this.loadAssets();
  }

  private loadAssets(): void {
    this.load.setPath('assets/');

    // Load floor tile sprites from PNG files (generated by sprite-generator)
    this.loadFloorTileSprites();

    // Load directional character sprites
    this.loadCharacterSprites();

    // Generate procedural textures for walls, formations, and entities
    this.generateTileTextures();
  }

  private loadCharacterSprites(): void {
    const directions = ['n', 'ne', 'e', 'se', 's', 'sw', 'w', 'nw'];
    for (const dir of directions) {
      this.load.image(`character-${dir}`, `sprites/character/character-${dir}.png`);
    }
  }

  private loadFloorTileSprites(): void {
    // Floor tile bases (8 biomes)
    const floorTiles = [
      'tile_void_floor',
      'tile_crystal_floor',
      'tile_toxic_floor',
      'tile_ruins_floor',
      'tile_ice_floor',
      'tile_volcanic_floor',
      'tile_fungal_floor',
      'tile_crater_floor',
    ];

    // Feature tiles (walls, pools, formations, etc.)
    const featureTiles = [
      'tile_void_wall',
      'tile_crystal_formation',
      'tile_toxic_pool',
      'tile_ruins_wall',
      'tile_ice_wall',
      'tile_lava',
      'tile_fungal_growth',
      'tile_crater_debris',
    ];

    // Load base floor tiles and their variants (_v2, _v3)
    for (const key of floorTiles) {
      this.load.image(key, `sprites/${key}.png`);
      this.load.image(`${key}_v2`, `sprites/${key}_v2.png`);
      this.load.image(`${key}_v3`, `sprites/${key}_v3.png`);
    }

    // Load feature tiles (no variants for now)
    for (const key of featureTiles) {
      this.load.image(key, `sprites/${key}.png`);
    }

    // Quest markers (will use procedural fallback if sprites don't exist)
    this.load.image('ui_quest_marker_available', 'sprites/ui_quest_marker_available.png');
    this.load.image('ui_quest_marker_ready', 'sprites/ui_quest_marker_ready.png');
  }

  private generateTileTextures(): void {
    const ENTITY_SIZE = 256; // Entity sprite size (matches 256x256 tiles)
    const graphics = this.make.graphics({ x: 0, y: 0 });

    // All tile textures now loaded from PNG - only generate entity textures

    // Player sphere fallback - used if character sprites fail to load
    const PLAYER_SIZE = 256;
    const center = PLAYER_SIZE / 2;
    const radius = 100;

    // Base sphere color
    graphics.fillStyle(0x7b68ee);
    graphics.fillCircle(center, center, radius);

    // Highlight (top-left) for 3D sphere effect
    graphics.fillStyle(0x9f8fff, 0.6);
    graphics.fillCircle(center - radius * 0.3, center - radius * 0.3, radius * 0.5);

    // Smaller bright highlight
    graphics.fillStyle(0xffffff, 0.4);
    graphics.fillCircle(center - radius * 0.4, center - radius * 0.4, radius * 0.2);

    // Dark edge (bottom-right) for depth
    graphics.lineStyle(4, 0x5040a0, 0.5);
    graphics.beginPath();
    graphics.arc(center, center, radius - 1, Math.PI * 0.1, Math.PI * 0.9);
    graphics.strokePath();

    // Outer ring for definition
    graphics.lineStyle(3, 0x3a2a7a, 0.8);
    graphics.strokeCircle(center, center, radius);

    graphics.generateTexture('player-fallback', PLAYER_SIZE, PLAYER_SIZE);
    graphics.clear();

    // Creature (centered for 256px sprite)
    const ec = ENTITY_SIZE / 2; // entity center = 128
    graphics.fillStyle(0xff4444);
    graphics.fillCircle(ec, ec, 80);
    graphics.generateTexture('creature', ENTITY_SIZE, ENTITY_SIZE);
    graphics.clear();

    // Mineral (centered square for 256px sprite)
    graphics.fillStyle(0x44ffff);
    graphics.fillRect(64, 64, 128, 128);
    graphics.generateTexture('mineral', ENTITY_SIZE, ENTITY_SIZE);
    graphics.clear();

    // Item (smaller circle centered for 256px sprite)
    graphics.fillStyle(0xffff44);
    graphics.fillCircle(ec, ec, 48);
    graphics.generateTexture('item', ENTITY_SIZE, ENTITY_SIZE);
    graphics.clear();

    // Plant (triangle centered for 256px sprite)
    graphics.fillStyle(0x44cc44); // green
    graphics.fillTriangle(
      ec, 32,     // top
      64, 224,    // bottom left
      192, 224    // bottom right
    );
    graphics.generateTexture('plant', ENTITY_SIZE, ENTITY_SIZE);
    graphics.clear();

    // Quest markers (fallback if PNG files don't exist)
    // These will be used if sprite loading fails
    const MARKER_SIZE = 64;
    const mc = MARKER_SIZE / 2; // marker center = 32

    // Available quest marker (yellow ! on transparent background)
    graphics.fillStyle(0xffcc00, 1);
    graphics.fillCircle(mc, mc, 28);
    graphics.lineStyle(3, 0x000000);
    graphics.strokeCircle(mc, mc, 28);
    const availableText = this.make.text({
      x: mc,
      y: mc,
      text: '!',
      style: {
        fontSize: '48px',
        fontStyle: 'bold',
        color: '#000000',
      },
    });
    availableText.setOrigin(0.5, 0.5);
    graphics.generateTexture('ui_quest_marker_available_fallback', MARKER_SIZE, MARKER_SIZE);
    availableText.destroy();
    graphics.clear();

    // Ready quest marker (cyan ? on transparent background)
    graphics.fillStyle(0x00ccff, 1);
    graphics.fillCircle(mc, mc, 28);
    graphics.lineStyle(3, 0x000000);
    graphics.strokeCircle(mc, mc, 28);
    const readyText = this.make.text({
      x: mc,
      y: mc,
      text: '?',
      style: {
        fontSize: '48px',
        fontStyle: 'bold',
        color: '#000000',
      },
    });
    readyText.setOrigin(0.5, 0.5);
    graphics.generateTexture('ui_quest_marker_ready_fallback', MARKER_SIZE, MARKER_SIZE);
    readyText.destroy();
    graphics.clear();

    // POI fallback textures (procedural icons)
    this.createPoiFallbackTextures();

    graphics.destroy();
  }

  private createPoiFallbackTextures(): void {
    const iconSize = 64;
    const ic = iconSize / 2; // icon center = 32

    // Anomaly - purple circle with star
    const anomalyGraphics = this.add.graphics();
    anomalyGraphics.fillStyle(0x9966ff, 1);
    anomalyGraphics.fillCircle(ic, ic, ic - 4);
    anomalyGraphics.lineStyle(3, 0xcc99ff, 1);
    anomalyGraphics.strokeCircle(ic, ic, ic - 4);
    // Inner star pattern (5-pointed star)
    anomalyGraphics.fillStyle(0xffffff, 0.8);
    const starRadius = iconSize / 4;
    const starPoints = 5;
    const starPath: number[] = [];
    for (let i = 0; i < starPoints * 2; i++) {
      const angle = (i * Math.PI) / starPoints - Math.PI / 2;
      const radius = i % 2 === 0 ? starRadius : starRadius / 2;
      starPath.push(ic + Math.cos(angle) * radius);
      starPath.push(ic + Math.sin(angle) * radius);
    }
    anomalyGraphics.fillPoints(starPath, true);
    anomalyGraphics.generateTexture('poi_anomaly_fallback', iconSize, iconSize);
    anomalyGraphics.destroy();

    // Cache - gold container/chest
    const cacheGraphics = this.add.graphics();
    cacheGraphics.fillStyle(0xd4a017, 1);
    cacheGraphics.fillRect(8, 20, iconSize - 16, iconSize - 28);
    cacheGraphics.fillStyle(0xffd700, 1);
    cacheGraphics.fillRect(12, 16, iconSize - 24, 8);
    cacheGraphics.lineStyle(3, 0x8b6914, 1);
    cacheGraphics.strokeRect(8, 20, iconSize - 16, iconSize - 28);
    cacheGraphics.generateTexture('poi_cache_fallback', iconSize, iconSize);
    cacheGraphics.destroy();

    // Landmark - blue beacon/pillar (triangle)
    const landmarkGraphics = this.add.graphics();
    landmarkGraphics.fillStyle(0x4488ff, 1);
    landmarkGraphics.fillTriangle(ic, 4, 12, iconSize - 8, iconSize - 12, iconSize - 8);
    landmarkGraphics.lineStyle(3, 0x66aaff, 1);
    landmarkGraphics.strokeTriangle(ic, 4, 12, iconSize - 8, iconSize - 12, iconSize - 8);
    landmarkGraphics.fillStyle(0xffffff, 0.7);
    landmarkGraphics.fillCircle(ic, iconSize / 3, 8);
    landmarkGraphics.generateTexture('poi_landmark_fallback', iconSize, iconSize);
    landmarkGraphics.destroy();
  }

  create(): void {
    this.scene.start('WorldScene');
  }
}
